name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Node.js Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-sample-ts-lib-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-sample-ts-lib-
    - name: Install Dependencies
      run: npm ci
    - name: Run ESLint
      run: npm run lint
    - name: Run Tests
      run: npm run test
      env:
        CI: true
